### ISSUE TITLE
Add repo 'submit-tx-via-tor'

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/meta#14]
Reddit user /u/hapticpilot created a script to submit raw Monero transactions over Tor. He asked me to propose to add it to the Monero-Ecosystem project, so i'm opening the request on his behalf. Read the [discussion on reddit](https://www.reddit.com/r/Monero/comments/9pjkh5/a_simple_script_to_make_monero_transactions_more/)

It's a simple bash script, and i temporarely uploaded it on my personal repository. If the members of this project feels like it, it can be transferred to the ecosystem. It needs maintainers, so, in case, any volunteer?

**[submit-tx-via-tor
](https://github.com/erciccione/submit-tx-via-tor)**

**Comment by erciccione** [comment]
@monero-ecosystem/maintainers

**Comment by skftn** [comment]
A few thoughts:

- Instead of using curl + proxy, you could use `torify` or any of the other network wrappers.
- Grepping output of curl for `status": "OK"` seems dirty. This does not allow for elaborate error messages.
- Curl default user-agent needs to be changed
- Like your to-do's state; raw tx file validation would be nice but probably annoying to implement in bash.
- 190 lines of Bash seems too much for it actually does

It is however a cool script and hapticpilot did a good job. I can offer to maintain it, but personally I would also like to rewrite it into something simpler - Python (with no dependencies).

Lets see what the author thinks.

**Comment by Lafudoci** [comment]
I'm not familiar with tor stuff, but this script should be useful before we have Kovri implementation. And I have no doubt to acknowledge this if @skftn is going to take care of it :D

**Comment by erciccione** [comment]
@skftn He gave a detailed reply to your comments. See on reddit: https://www.reddit.com/r/Monero/comments/9pjkh5/a_simple_script_to_make_monero_transactions_more/e8698qf/

Please reply there so that we have theconversation on just one platform and i don't have to be the go-between :)

**Comment by skftn** [comment]
Lets get this into the ecosystem. Ill maintain it. Ill also add a Python version, not as a rewrite but as an additional script one could choose to use :)

**Comment by erciccione** [comment]
Approved
We have consensus (4 ACK). Will transfer the repo and set @skftn as maintainer

**Comment by erciccione** [comment]
- Repo transferred to the ecosystem.
- @skftn Is now the maintainer/administrator
- Added to the list of the repos with #15 

Thank you all
