### ISSUE TITLE
Add go-monero-rpc-client repository

### ISSUE THREAD

**Issue by omani** [monero-ecosystem/meta#35]
hello dear monero community,
I have written a client for the monero RPC (wallet and daemon) in golang.

I'd like to add it to the monero ecosystem :)

you can find my repository at https://github.com/omani/go-monero-rpc-client/

**Comment by erciccione** [comment]
Hi @omani, thanks for reaching out! I took a quick look and the code looks really well commented, but I'll let the other maintainers with more coding expertise to give their opinion on the code itself. I can just say that i haven't seen an implementation in golang of the RPC wallet and daemon and i think would be cool to have it in the Ecosystem :)

Pinging maintainers as for our governance system: @monero-ecosystem/maintainers

**Comment by Lafudoci** [comment]
Having new implementation is always a good step for ecosystem. The project looks well documented, good job! `ACK`

**Comment by rbrunner7** [comment]
Nice work. This could have the potential to become *the* preferred Go bindings for the Monero wallet RPC.

But something bothers me, just out of principle. Maybe I am oversensitive here, but still:

I happen to work intensively with Ochsenhofer's [go-monero package](https://github.com/gabstv/go-monero) for the last 3 weeks or so and have even added some still missing calls myself in my so-far local fork. That's why I know that code quite well in the meantime.

You say that your package is "inspired" by that package. Are you sure it's only that, "inspired"? I got the impression that you started with a fork of that code.

There is for example the *second* code example in your README, the one with logging in. It contains this code line:

     t := httpdigest.New("test", "testpass")

Well, `httpdigest` is from another package that Ochsenhofer wrote, [this one](https://github.com/gabstv/httpdigest). You don't have that, or do not have that yet.

Or compare [this "gabstv" file](https://github.com/gabstv/go-monero/blob/master/walletrpc/util.go) with [your file of the same name](https://github.com/omani/go-monero-rpc-client/blob/master/wallet/util.go).

If you really started with a fork, may I kindly propose to honor Ochsenhofer's MIT license and include his copyright in your license file?

**Comment by omani** [comment]
hi @rbrunner7 yes it is a fork. I extended it to have all methods of the recent version of the monero rpc.

I think I understand what you mean. I didn't respect the copyright of the project I forked from. I will fix that by including the MIT license file of him.

this is due to the lack of my understanding of the MIT license. pardon me.

**Comment by omani** [comment]
I've fixed the LICENSE file. :+1:

**Comment by rbrunner7** [comment]
Nice, that's the reasonable and respecting reaction that I hoped for :)

I am no specialist in licensing, but as your extensions after forking are quite substantial, I think it would be appropriate to list both you and Ochsenhofer now as copyright holders, along the lines mentioned in this [StackExchange answer](https://softwareengineering.stackexchange.com/questions/386582/altering-author-names-in-mit-license):

    Copyright (c) 2018 <original author>
    Copyright (c) 2019 <new author>

**Comment by omani** [comment]
thanks for the information. I've put me in there as you suggested.

**Comment by rbrunner7** [comment]
I have now looked over the code and saw nothing suprising or even suspicious: It is what it says it is, and it's nice to have now such complete and nicely commented Go bindings. I vote for inclusion into the Monero Ecosystem.

**Comment by erciccione** [comment]
Thanks @Lafudoci and especially @rbrunner7 for the deep analysis.

I consider the proposal approved. 

I'm gonna leave this open for 24 more hours in case somebody else have a last minute comment, then we can start the transfer @omani :).

**Comment by erciccione** [comment]
@omani I added you as a member of the Monero Ecosystem project. From now on, you'll be able to express your vote anytime is necessary to reach consensus to make a decision (for example, when adding and removing repositories from the Ecosystem). See our goverance system for more info.

After accepting the invitation, you will be able to transfer the repository. Please ping me here when done. Thank you and welcome! :)

**Comment by Lafudoci** [comment]
@omani Please also take a look at our [ecosystem page](https://github.com/monero-ecosystem/monero-ecosystem.github.io). Feel free to add your repo card if you like it.

**Comment by omani** [comment]
hi @Lafudoci,
I've transfered my repo to the monero-ecosystem. I want to create a markdown file in _posts but I just can't figure out what my maintainer_uid is. any idea where I can find this uid?

**Comment by omani** [comment]
I opened a PR on the ecosystem page repo.

**Comment by erciccione** [comment]
Repo added in the readme with #36 and [Announced on reddit](https://www.reddit.com/r/Monero/comments/bqtrj5/gomonerorpcclient_a_client_for_the_monero_rpc/). Welcome @omani :) !

If you want, please set your membership to the Ecosystem as public [here](https://github.com/orgs/monero-ecosystem/people), so that you will have the "Monero Ecosystem" badge on your profile and the project will be more visible.
