### ISSUE TITLE
Add monero-rpc-rs to Ecosystem

### ISSUE THREAD

**Issue by vorot93** [monero-ecosystem/meta#38]
This is a Rust client for the wallet and daemon RPC that I created for the purpose of easy and type-safe integration of Monero into Rust-based web services. While it closely mirrors jsonrpc protocol documented in the Developer guides, it strives to be as Rust-idiomatic as well.

https://github.com/vorot93/monero-rpc-rs

**Comment by erciccione** [comment]
Hi @vorot93 , thanks for reaching out :)

Let's ping the @monero-ecosystem/maintainers and see what they think about it.
This would be also the first repository in Rust. monero-rpc-rs would be a nice addition to our pool of programming languages.

**Comment by normoes** [comment]
I think, the more integration into different languages the better.
Could be the starting point for other projects written in Rust.

**Comment by lh1008** [comment]
Agree with @normoes :+1:

**Comment by erciccione** [comment]
Thank you @normoes @lh1008 . I'm gonna wait a couple more days before labelling this as "accepted", some more feedbacks would be appreciated.

**Comment by erciccione** [comment]
Thank you for your feedback @normoes @lh1008 :)

@vorot93 It's ok to be added for me, if you intend to keep the repository updated :)

**Comment by vorot93** [comment]
@erciccione I do although hopefully I won't be alone. :)

**Comment by erciccione** [comment]
Since there are no other comments, we can consider this repository approved.

@vorot93 I sent you an invitation to become member of the team, please accept. After, you can start the transfer of the repository to the monero-ecosystem project. See https://help.github.com/en/articles/transferring-a-repository.

Once the repo is transferred, you are at all effect a member of the Ecosystem project, and you have right to vote for the inclusion/removal of other projects or vote for substantial changes to the Ecosystem. Thank you :)

You may want to add your repository to moneroecosystem.org (repo [here](monero-ecosystem/monero-ecosystem.github.io))

**Comment by erciccione** [comment]
The repo is transferred. I'm gonna add it to the meta repo and then announce it.

@vorot93 Please make your membership public here: https://github.com/orgs/monero-ecosystem/people. So that you will have the Monero Ecosystem badge on your profile. That will help to give some visibility to the project.

**Comment by erciccione** [comment]
Announced on [Reddit](https://www.reddit.com/r/Monero/comments/c22tnf/a_new_project_joins_the_monero_ecosystem/) and [Twitter](https://twitter.com/calciferciccio/status/1140988214586552320).

This issue is resolved :)
