### ISSUE TITLE
Rename "monero-rpc-rs" and "go-monero-rpc-client" to follow more common naming convention

### ISSUE THREAD

**Issue by dginovker** [monero-ecosystem/meta#53]
`monero-javascript`, `monero-python` and `monero-java` all follow the same name to imply they're libraries for the Monero RPC(s) in their respective language, but `monero-rpc-rs` and `go-monero-rpc-client` don't follow suite. Thoughts on changing this?

**Comment by erciccione** [comment]
I think better ping the maintainers: @omani @vorot93

**Comment by vorot93** [comment]
There is already a [monero-rs](https://github.com/monero-rs/monero-rs) library so I will not accept this proposal.

**Comment by erciccione** [comment]
@vorot93 I don't think it's necessary to close this issue just yet, i'm reopening it. I think a solution can be discussed, beside the fact that we are still waiting for an input from @omani :)

**Comment by omani** [comment]
hi all,
the reason why I chose the name is because of kind of the naming convention known in the go community. wrappers/libs/modules to external things usually start with `go` or `go-` to imply a golang version of the application or third party lib/package.

I like the way it sounds, compact and clear and you know what is expecting you: a golang client for the monero rpc. `go-monero-rpc-client`

:)

**Comment by dginovker** [comment]
I'm willing to close this proposal given there is reasoning behind the names. Thanks to @omani and @vorot93.

Close ping @erciccione
