### ISSUE TITLE
Do we have a youtube account?

### ISSUE THREAD

**Issue by omani** [monero-ecosystem/meta#55]
hi folks,
do we have a youtube account? I would like to be able to publish my videos related to my projects to a common place on youtube. favorably a monero-ecosystem youtube channel.

do you like this idea? if not, where can I upload videos to my projects and link them in eg. my readmes, links, etc. (in regards to the monero-ecosystem)?

if you do like the idea, let's talk about who will control or own the youtube channel and who will be in charge of maintaining it. and who will be the person to speak to if the @monero-ecosystem/maintainers want to upload a video in general.

and please don't rush and go and enthusiastically create a channel and say "look guys. I just created one. let's use this". anyone can do that. that is not the point.

let's just first talk about it.

thanks
omani

**Comment by erciccione** [comment]
We don't have one, but we can create it. I thought about opening a twitter account some time ago, where @monero-ecosystem/maintainers can publish new releases and announcements for their project. I didn't do it because i wasn't sure it would have been used.

If you plan to use the channel, i think would be a good idea to create it. Each of us could use it and maybe the credentials could be shared between the members. Let's see what the other @monero-ecosystem/maintainers think about it.

**Comment by lh1008** [comment]
I like the idea. Having a place in youtube for the Monero-Ecosystem projects to post will be great. I have been planning about some tutorials in the future but haven't put myself into it due to my reduced time I have at the moment but I do support the initiative.

**Comment by xanoni** [comment]
If this moves forward I would keep good local copies of everything, because it will be de-platformed eventually.
